modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="nocheatenchant"
version="${file.jarVersion}"
displayName="NoCheatEnchant"
description='''Adds a command to enchant the item in the player's main hand.'''

[[dependencies.nocheatenchant]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.nocheatenchant]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"